name: todoey_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.0.0
  fluttertoast: ^8.0.3
  google_mobile_ads: ^0.12.1
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  lint: ^1.3.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  reorderables: ^0.4.0
  shimmer: ^2.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

