name: todoey_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">2.11.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.1
  shimmer: ^1.1.1
  hive:
  hive_flutter:
  path_provider: ^1.6.11
  reorderables: ^0.3.2
  fluttertoast: ^7.0.1
  lint: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - images/

