name: todoey_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ">2.11.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^5.0.0
  shimmer: ^1.1.1
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  reorderables: ^0.4.0
  fluttertoast: ^8.0.3
  flutter_keyboard_visibility: ^5.0.0
  lint: ^1.3.0
  google_mobile_ads: ^0.11.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - images/

